name: flutter_chat_app
description: FlutterChatApp

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  provider: ^6.0.5
  google_fonts: ^4.0.3
  firebase_core: ^2.7.0
  flutter_lints: ^2.0.0
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.5
  uuid: ^3.0.4
  firebase_database: ^10.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo.png

